### ISSUE TITLE
Bootstrap load order

### ISSUE THREAD

**Issue by smlparry** [doublesecretagency/craft-bootstrap#1]
Hey there,

I am having an issue where the bootstrap css is being included after my `includeCssFile` tag. This means I cannot overwrite default bootstrap styles.

Here is what is rendered:
![screen shot 2018-08-03 at 12 39 45 pm](https://user-images.githubusercontent.com/7920702/43621359-543a90d6-971a-11e8-9326-64fdce090163.png)

Here is what I've specified in my code:
![screen shot 2018-08-03 at 11 59 37 am](https://user-images.githubusercontent.com/7920702/43620203-e8b3e2b8-9714-11e8-8883-ffc64e12be70.png)

And I have turned off the auto-load
![screen shot 2018-08-03 at 12 00 13 pm](https://user-images.githubusercontent.com/7920702/43620212-f3dac724-9714-11e8-905e-e8af2a6fa03a.png)

Is this a known issue? If not, how do I correct the order?

**Comment by lindseydiloreto** [comment]
Hi Samuel,

Try this... remove the `includeCssFile` tag, and replace it with this...

```twig
{% do view.registerCssFile('assets/styles/main.css', {
    depends: ['doublesecretagency\\bootstrap\\web\\assets\\BootstrapAssets']
}) %}
```

This tells Craft to load your CSS file _after_ the `BootstrapAssets` have been loaded.

Hope that helps!

**Comment by lindseydiloreto** [comment]
This is now supported a little better, and documented here...

https://github.com/doublesecretagency/craft-bootstrap#make-sure-your-custom-css-andor-js-loads-last
